//
// Created by Милена Булкина on 06.03.2021.
//

#ifndef ONE_DIMENSIONAL_OPTIMIZATION_METHODS_DICHOTOMYOPTIMIZATIONMETHOD_H
#define ONE_DIMENSIONAL_OPTIMIZATION_METHODS_DICHOTOMYOPTIMIZATIONMETHOD_H


class DichotomyOptimizationMethod {

};


#endif //ONE_DIMENSIONAL_OPTIMIZATION_METHODS_DICHOTOMYOPTIMIZATIONMETHOD_H
